version: 2.1

orbs:
  python: circleci/python@0.2.1
  py: nic30/python-all-in-1@0.2.17

jobs:
  install-and-test:
    executor: python/default
    resource_class: small
    steps:
      - checkout
      # - python/load-cache
      - py/install-package-git:
          cwd: ..
          url: https://github.com/Nic30/hwtLib
      - py/install-setup-py
      # - python/save-cache
      - py/test-and-coverage

  deploy:
    executor: python/default
    steps:
      - py/deploy-pypi

workflows:
  main:
    jobs:
      - install-and-test
      - deploy:
         requires:
           - install-and-test
         filters:
           tags:
             only: /v[0-9]+(\.[0-9]+)*/
           branches:
             ignore: /.*/
